[workspace]

members = [
    "kvserver",
    "raft-utils",
    "raft-core",
]


[workspace.dependencies]
serde_json = "1.0"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
futures = "0.3"
anyhow = "1.0"
async-std = { version = "1.9", features = ["attributes"] }