systemLog:
  destination: "console"
  path: "raft.log"
  debug: true
    
replication:
  id: "raft"
  members:
  - id: 0
    host: "127.0.0.1:30000"
    me: true
  - id: 1
    host: "127.0.0.1:31000"
  - id: 2
    host: "127.0.0.1:32000"
  - id: 3
    host: "127.0.0.1:33000"
  - id: 4
    host: "127.0.0.1:34000"

  verbosity:
    election: true
    heartbeats: true
  
      
    

