[package]
name = "raft-utils"
version = "0.1.0"
authors = ["Styvane Soukossi <styvane@acm.org>"]
edition = "2018"


[dependencies]
anyhow = "1.0"
tokio = { version = "1", features = ["rt", "net", "macros", "io-util"] }