[package]
name = "raft-utils"
version = "0.1.0"
authors = ["Styvane Soukossi <styvane@acm.org>"]
edition = "2021"
rust-version = "1.64"


[dependencies]
anyhow = { workspace = true }
async-std = { workspace = true }
