[package]
name = "raft-core"
version = "0.1.0"
authors = ["Styvane Soukossi <styvane@acm.org>"]
edition = "2018"


[dependencies]
anyhow = "1.0"
config = "0.11"
serde_json = "1.0"
rand = "0.8.0"


[dependencies.raft-utils]
path = "../raft-utils"


[dependencies.serde]
version = "1.0"
features = ["derive"]


[dependencies.async-std]
version = "1.9"
features = ["attributes"]